/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-20 00:17:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/top.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- js파일 참조-------------------------------- -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/userCheck.js\"></script>\r\n");
      out.write("<!-- ------------------------------------------ -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<h1>회원 가입</h1>\r\n");
      out.write("	<form name=\"mf\" action=\"joinEnd.jsp\" method=\"post\">\r\n");
      out.write("	<!-----활동회원: mode(0), 관리자(9)--------------------->\r\n");
      out.write("	<input type=\"hidden\" name=\"mode\" value=\"0\">\r\n");
      out.write("	<!------------------------------------------------->\r\n");
      out.write("	<table id=\"userTable\" border=\"1\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>이  름</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"text\" name=\"name\" id=\"name\"\r\n");
      out.write("			 placeholder=\"Name\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<span class=\"ck\">*이름은 한글만 가능해요</span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>아이디</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"text\" name=\"userid\" id=\"userid\" readonly\r\n");
      out.write("			 placeholder=\"User ID\">\r\n");
      out.write("			 <button type=\"button\" onclick=\"open_idcheck()\">아이디 중복 체크</button>\r\n");
      out.write("			<br>\r\n");
      out.write("			<span class=\"ck\">*아이디는 영문자,숫자,_,!만 사용 가능해요</span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>비밀번호</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"password\" name=\"pwd\" id=\"pwd\"\r\n");
      out.write("			 placeholder=\"Password\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<span class=\"ck\">*비밀번호는 문자,숫자,!,.포함해서 4~8자 이내</span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>비밀번호 확인</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"password\" name=\"pwd2\" id=\"pwd2\"\r\n");
      out.write("			 placeholder=\"Re Password\">\r\n");
      out.write("			<br>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>연락처</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"text\" name=\"hp1\" id=\"hp1\" placeholder=\"HP1\" maxlength=\"3\">-\r\n");
      out.write("			<input type=\"text\" name=\"hp2\" id=\"hp2\" placeholder=\"HP2\" maxlength=\"4\">-\r\n");
      out.write("			<input type=\"text\" name=\"hp3\" id=\"hp3\" placeholder=\"HP3\" maxlength=\"4\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<span class=\"ck\">*앞자리(010|011)중에 하나-(숫자 3~4자리)-(숫자 4자리)\r\n");
      out.write("			만 가능해요\r\n");
      out.write("			</span>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>우편번호</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"text\" name=\"post\" id=\"post\"\r\n");
      out.write("			 placeholder=\"Post\" maxlength=\"5\">\r\n");
      out.write("			 <button type=\"button\" onclick=\"\">우편번호 찾기</button>\r\n");
      out.write("			<br>			\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"20%\" class=\"m1\"><b>주  소</b></td>\r\n");
      out.write("			<td width=\"80%\" class=\"m2\">\r\n");
      out.write("			<input type=\"text\" name=\"addr1\" id=\"addr1\"\r\n");
      out.write("			 placeholder=\"Address1\" style=\"margin-bottom:5px;\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<input type=\"text\" name=\"addr2\" id=\"addr2\"\r\n");
      out.write("			 placeholder=\"Address2\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td colspan=\"2\" class=\"m2\" style=\"text-align:center\">\r\n");
      out.write("				<button type=\"button\" onclick=\"member_check()\">회원가입</button>\r\n");
      out.write("				<button type=\"reset\">다시쓰기</button>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/foot.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
