DESC MEMO;
SELECT * FROM MEMO;

일련번호를 생성해주는 객체 - SEQUENCE
--CREATE SEQUENCE 시퀀스명
--START WITH 시작수
--INCREMENT BY 증가값

CREATE SEQUENCE MEMO_SEQ
START WITH 3
INCREMENT BY 1;

시퀀스의 속성
--NEXTVAL:다음에 증가할 값을 반환
--CURRVAL:현재 가지고 잇는 값을 반환, NEXTVAL이 한번 불러진 다음에만 사용가능

INSERT INTO MEMO(NO, NAME, MSG)
VALUES(MEMO_SEQ.NEXTVAL,'CHALLY','HELLO');
COMMIT;
SELECT * FROM MEMO;

SELECT MEMO_SEQ.CURRVAL FROM DUAL;